#ifndef _GAMEDEFINE_LOUDSPEAKER_H_
#define _GAMEDEFINE_LOUDSPEAKER_H_

// 小喇叭缓冲池上限
#define  LOUDSPEAKER_POOL_MAX	128

// 每个小喇叭最少显示时间--数量阶梯
#define LOUDSPEAKER_PHASE_NUM_1 0
#define LOUDSPEAKER_PHASE_NUM_2 11
#define LOUDSPEAKER_PHASE_NUM_3 31
#define LOUDSPEAKER_PHASE_NUM_4 61

// 每个小喇叭最少显示时间--具体时间 单位:秒
#define LOUDSPEAKER_PHASE_TIME_1 10
#define LOUDSPEAKER_PHASE_TIME_2 8
#define LOUDSPEAKER_PHASE_TIME_3 6
#define LOUDSPEAKER_PHASE_TIME_4 4

#define QIANLICHUANYIN_DATAID 4031

#endif
