// Generated by the protocol buffer compiler.  DO NOT EDIT!

#ifndef PROTOBUF_RceAddArmy_2eproto__INCLUDED
#define PROTOBUF_RceAddArmy_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "Army.pb.h"

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RceAddArmy_2eproto();
void protobuf_AssignDesc_RceAddArmy_2eproto();
void protobuf_ShutdownFile_RceAddArmy_2eproto();

class RceAddArmy;

// ===================================================================

class RceAddArmy : public ::google::protobuf::Message {
 public:
  RceAddArmy();
  virtual ~RceAddArmy();
  
  RceAddArmy(const RceAddArmy& from);
  
  inline RceAddArmy& operator=(const RceAddArmy& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RceAddArmy& default_instance();
  void Swap(RceAddArmy* other);
  
  // implements Message ----------------------------------------------
  
  RceAddArmy* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RceAddArmy& from);
  void MergeFrom(const RceAddArmy& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);
  
  // repeated .Army army = 2;
  inline int army_size() const;
  inline void clear_army();
  static const int kArmyFieldNumber = 2;
  inline const ::google::protobuf::RepeatedPtrField< ::Army >& army() const;
  inline ::google::protobuf::RepeatedPtrField< ::Army >* mutable_army();
  inline const ::Army& army(int index) const;
  inline ::Army* mutable_army(int index);
  inline ::Army* add_army();
  
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 type_;
  ::google::protobuf::RepeatedPtrField< ::Army > army_;
  friend void  protobuf_AddDesc_RceAddArmy_2eproto();
  friend void protobuf_AssignDesc_RceAddArmy_2eproto();
  friend void protobuf_ShutdownFile_RceAddArmy_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static RceAddArmy* default_instance_;
};
// ===================================================================


// ===================================================================


// ===================================================================

// RceAddArmy

// optional int32 type = 1;
inline bool RceAddArmy::has_type() const {
  return _has_bit(0);
}
inline void RceAddArmy::clear_type() {
  type_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 RceAddArmy::type() const {
  return type_;
}
inline void RceAddArmy::set_type(::google::protobuf::int32 value) {
  _set_bit(0);
  type_ = value;
}

// repeated .Army army = 2;
inline int RceAddArmy::army_size() const {
  return army_.size();
}
inline void RceAddArmy::clear_army() {
  army_.Clear();
}
inline const ::google::protobuf::RepeatedPtrField< ::Army >&
RceAddArmy::army() const {
  return army_;
}
inline ::google::protobuf::RepeatedPtrField< ::Army >*
RceAddArmy::mutable_army() {
  return &army_;
}
inline const ::Army& RceAddArmy::army(int index) const {
  return army_.Get(index);
}
inline ::Army* RceAddArmy::mutable_army(int index) {
  return army_.Mutable(index);
}
inline ::Army* RceAddArmy::add_army() {
  return army_.Add();
}


#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

#endif  // PROTOBUF_RceAddArmy_2eproto__INCLUDED
