//This code create by CodeEngine Author:Wendy ,don't modify

#include "PacketDefine.h"
 #include "Base.h"
 
 namespace Packets
 {
 typedef FLString<MAX_PACKET_NAME_SIZE> PACKETNAMESTR;
 PACKETNAMESTR g_PacketNameVector[PACKET_MAX];
 void InitPacketNameVector()
 {
 g_PacketNameVector[PACKET_NONE] = "PACKET_NONE";
 g_PacketNameVector[PACKET_CG_LOGIN_PAK] = "PACKET_CG_LOGIN_PAK";
 g_PacketNameVector[PACKET_GC_LOGIN_RET_PAK] = "PACKET_GC_LOGIN_RET_PAK";
 g_PacketNameVector[PACKET_CG_CONNECTED_HEARTBEAT_PAK] = "PACKET_CG_CONNECTED_HEARTBEAT_PAK";
g_PacketNameVector[PACKET_GC_CONNECTED_HEARTBEAT_PAK] = "PACKET_GC_CONNECTED_HEARTBEAT_PAK";
g_PacketNameVector[PACKET_CG_REQ_NEAR_LIST_PAK] = "PACKET_CG_REQ_NEAR_LIST_PAK";
g_PacketNameVector[PACKET_GC_NEAR_MARCHLIST_PAK] = "PACKET_GC_NEAR_MARCHLIST_PAK";
g_PacketNameVector[PACKET_CG_CHAT_PAK] = "PACKET_CG_CHAT_PAK";
g_PacketNameVector[PACKET_GC_CHAT_PAK] = "PACKET_GC_CHAT_PAK";
g_PacketNameVector[PACKET_GC_NOTICE_PAK] = "PACKET_GC_NOTICE_PAK";
g_PacketNameVector[PACKET_GC_UPDATE_SCENE_INSTACTIVATION_PAK] = "PACKET_GC_UPDATE_SCENE_INSTACTIVATION_PAK";
g_PacketNameVector[PACKET_CG_MOVE_PAK] = "PACKET_CG_MOVE_PAK";
g_PacketNameVector[PACKET_GC_MOVE_PAK] = "PACKET_GC_MOVE_PAK";
g_PacketNameVector[PACKET_GC_STOP_PAK] = "PACKET_GC_STOP_PAK";
g_PacketNameVector[PACKET_GC_TELEMOVE_PAK] = "PACKET_GC_TELEMOVE_PAK";
g_PacketNameVector[PACKET_CG_SKILL_USE_PAK] = "PACKET_CG_SKILL_USE_PAK";
g_PacketNameVector[PACKET_GC_RET_USE_SKILL_PAK] = "PACKET_GC_RET_USE_SKILL_PAK";
g_PacketNameVector[PACKET_GC_UPDATE_ANIMATION_STATE_PAK] = "PACKET_GC_UPDATE_ANIMATION_STATE_PAK";
g_PacketNameVector[PACKET_GC_DELETE_OBJ_PAK] = "PACKET_GC_DELETE_OBJ_PAK";
g_PacketNameVector[PACKET_GC_ATTACKFLY_PAK] = "PACKET_GC_ATTACKFLY_PAK";
g_PacketNameVector[PACKET_GC_FORCE_SETPOS_PAK] = "PACKET_GC_FORCE_SETPOS_PAK";
g_PacketNameVector[PACKET_GC_UPDATE_NEEDIMPACTINFO_PAK] = "PACKET_GC_UPDATE_NEEDIMPACTINFO_PAK";
g_PacketNameVector[PACKET_GC_PLAY_EFFECT_PAK] = "PACKET_GC_PLAY_EFFECT_PAK";
g_PacketNameVector[PACKET_GC_REMOVEEFFECT_PAK] = "PACKET_GC_REMOVEEFFECT_PAK";
g_PacketNameVector[PACKET_CG_FIGHT_PAK] = "PACKET_CG_FIGHT_PAK";
g_PacketNameVector[PACKET_CG_LEAVE_COPYSCENE_PAK] = "PACKET_CG_LEAVE_COPYSCENE_PAK";
g_PacketNameVector[PACKET_CG_ROBOT_OPEN_PAK] = "PACKET_CG_ROBOT_OPEN_PAK";
g_PacketNameVector[PACKET_GC_ROBOT_OPEN_PAK] = "PACKET_GC_ROBOT_OPEN_PAK";
g_PacketNameVector[PACKET_CG_ASSIGN_HERO_PAK] = "PACKET_CG_ASSIGN_HERO_PAK";
g_PacketNameVector[PACKET_GC_ASSIGN_HERO_PAK] = "PACKET_GC_ASSIGN_HERO_PAK";
g_PacketNameVector[PACKET_CG_SEND_MARCH_PAK] = "PACKET_CG_SEND_MARCH_PAK";
g_PacketNameVector[PACKET_GC_SEND_MARCH_PAK] = "PACKET_GC_SEND_MARCH_PAK";
g_PacketNameVector[PACKET_CG_CREATEROLE_PAK] = "PACKET_CG_CREATEROLE_PAK";
g_PacketNameVector[PACKET_GC_CREATEROLE_RET_PAK] = "PACKET_GC_CREATEROLE_RET_PAK";
g_PacketNameVector[PACKET_GC_LOGIN_QUEUE_STATUS_PAK] = "PACKET_GC_LOGIN_QUEUE_STATUS_PAK";
g_PacketNameVector[PACKET_CG_BATTLEINFOR_PAK] = "PACKET_CG_BATTLEINFOR_PAK";
g_PacketNameVector[PACKET_GC_OBJINFOR_PAK] = "PACKET_GC_OBJINFOR_PAK";
g_PacketNameVector[PACKET_GC_BATTLEINFOR_PAK] = "PACKET_GC_BATTLEINFOR_PAK";
g_PacketNameVector[PACKET_GC_OBJPOSLIST_PAK] = "PACKET_GC_OBJPOSLIST_PAK";
g_PacketNameVector[PACKET_CG_OBJPOSLIST_PAK] = "PACKET_CG_OBJPOSLIST_PAK";
g_PacketNameVector[PACKET_GC_OBJCOMMANDPURSUE_PAK] = "PACKET_GC_OBJCOMMANDPURSUE_PAK";
g_PacketNameVector[PACKET_GC_OBJPREPAREFORATTACK_PAK] = "PACKET_GC_OBJPREPAREFORATTACK_PAK";
g_PacketNameVector[PACKET_GC_OBJGETHURT_PAK] = "PACKET_GC_OBJGETHURT_PAK";

 }
 const tchar* GetPacketNameByID(tint32 nPacketID)
 {
 if(nPacketID>=0 && nPacketID<Packets::PACKET_MAX)
 {
 return g_PacketNameVector[nPacketID].GetCText();
 }
 return "";
 }
 }
