#include "BaseUtility.h"

BSARRAY_ASSIGN_IMPL(tint16,10);
BSARRAY_ASSIGN_IMPL(tint32,2);
BSARRAY_ASSIGN_IMPL(tint32,6);
BSARRAY_ASSIGN_IMPL(tint32,8);
BSARRAY_ASSIGN_IMPL(tint32,9);
BSARRAY_ASSIGN_IMPL(tint32,15);
BSARRAY_ASSIGN_IMPL(tint32,17);
BSARRAY_ASSIGN_IMPL(tint32,30);
BSARRAY_ASSIGN_IMPL(tfloat32,9);