#include "BaseUtility.h"

BSARRAY_ASSIGN_IMPL(short,10);
BSARRAY_ASSIGN_IMPL(int,2);
BSARRAY_ASSIGN_IMPL(int,6);
BSARRAY_ASSIGN_IMPL(int,8);
BSARRAY_ASSIGN_IMPL(int,15);
BSARRAY_ASSIGN_IMPL(int,17);
BSARRAY_ASSIGN_IMPL(int,30);
BSARRAY_ASSIGN_IMPL(float,17);