#ifndef _GAMEDEFINE_CHAT_H_
#define _GAMEDEFINE_CHAT_H_

//发言最大字符数
#define	 CHAT_SIZE_MAX_WORLD 121	// 40*3+1
#define  CHAT_SIZE_MAX	385			// 128*3+1

//世界发言CD 120s
#define  WORLDCHAT_CDTIME			120
#define  WORLDCHAT_CDTIME_UNDER30	240

#define  VOICECHAT_MAXSIZE 10240
#define  VOICECHAT_SERVER_MAXCOUNT 40000

//世界发言等级区分
#define  WORLDCHAT_CDLEVEL	30

#define  WORLDCHAT_LEVELLIMIT	10

#define  CHANNELID_LENGTH_MAX	128

#endif // !_GAMEDEFINE_CHAT_H_
